// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPyB9DR41rs4ZJm5GoeQiYOF1TlG6mGlo',
    appId: '1:1046645107550:web:3f515370690a8bb4067dcf',
    messagingSenderId: '1046645107550',
    projectId: 'ligretto-97b63',
    authDomain: 'ligretto-97b63.firebaseapp.com',
    storageBucket: 'ligretto-97b63.appspot.com',
    measurementId: 'G-5ED3HB1C3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF3-cuKcPzICHB0gK5TvlWjhxR93APZts',
    appId: '1:1046645107550:android:a81118adac9d58be067dcf',
    messagingSenderId: '1046645107550',
    projectId: 'ligretto-97b63',
    storageBucket: 'ligretto-97b63.appspot.com',
  );
}
